-- Disable Row Level Security (RLS) on all tables to allow public access (for development/demo)
-- Run this in the Supabase SQL Editor

ALTER TABLE "User" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Customer" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceProvider" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Job" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Review" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Service" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "JobLocation" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Requests" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Involves" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Requires" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Provides" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Writes" DISABLE ROW LEVEL SECURITY;

-- Verify it works
SELECT 'RLS Disabled successfully' as message;
